// THIS IS MY JQUERY CODE FOR MY MAIN PAGE AND ITS USED FOR ITS MAIN FUNCTION//

$("#btnMainSearch").click(function mainSearch() {
    console.log("Calculating position...");
});

// HERE I WILL WIRTE THE CODE FOR MY GEOLOC API COMBINE MY LOC WITH THE LOC OF MY SURROUUNDING PHARMACIES



//ONCE I HAVE MY LOC I WILL USE THE CLASS NEAR LOCATION TO FIND THE 3 MOST CLOSE PHARMACIES

